import Head from 'next/head'
import Header from "../src/components/Header";
import About from '../src/components/About';
import Footer from '../src/components/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Digital Setup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Header />
      <main>
        <About />
      </main>
      <Footer />

    </div>
  )
}
